### ISSUE TITLE
Lost tabs on Session Restore

### ISSUE THREAD

**Issue by yfdyh000** [aghorler/LoadTabOnSelect#1]
If the browser is closed with pending tabs, the user will lose these tabs.

You should persist the `managedTabs` using storage or url (like [tab-suspender](https://github.com/rNeomy/tab-suspender)).

**Comment by a8763506128977812212307169331690** [comment]
Thanks.

I didn't consider this, because I don't personally save tabs across sessions.

I will attempt to implement this in the next few days.

**Comment by a8763506128977812212307169331690** [comment]
Hi.

I've changed unloaded tab storage to a tab url, rather than depending on an array.

This should resolve this issue.
